name: 2024.08-q2-itn-Workshop
channels:
- https://packages.qiime2.org/qiime2/2024.5/amplicon/passed
- conda-forge
- bioconda
- defaults
dependencies:
  - qiime2-amplicon
  - pip:
    - jupyter-book
    - q2doc @ git+https://github.com/qiime2/sphinx-ext-qiime2.git@master
    - sphinx-exercise
